apiVersion: v1
kind: Pod 
metadata:
  name: test-affinity
spec:
  containers:
  - image: debian:latest
    imagePullPolicy: IfNotPresent
    name: nginx
    command: ["/bin/sh"]
    args:
      - "-c"
      - "while true; do sleep 10;done"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: k
            operator: In
            values:
            - v