apiVersion: v1
kind: Pod 
metadata:
  name: test
spec:
  containers:
  - image: debian:latest
    imagePullPolicy: IfNotPresent
    name: test
    command: ["/bin/sh"]
    args:
      - "-c"
      - "while true; do sleep 10;done"