apiVersion: v1
kind: Pod 
metadata:
  name: test
spec:
  containers:
  - image: debian:latest
    imagePullPolicy: IfNotPresent
    name: nginx
    command: ["/bin/sh"]
    args:
      - "-c"
      - "while true; do sleep 10;done"
    securityContext:
      privileged: true
    volumeDevices:
    - devicePath: /my-disk
      name: example-local-claim
  volumes:
  - name: example-local-claim
    persistentVolumeClaim:
      claimName: example-local-claim