kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim
spec:
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 0.5Gi