apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "10G"
        cpu: "500m"
      limits:
        memory: "10G"
        cpu: "500m"
