    

apiVersion: v1
kind: Pod 
metadata:
  name: script-pod
spec:
  containers:
  - image: debian
    name: debian
    command:
      - /bin/bash
      - -c
      - |
        trap "echo Caught SIGTERM; sleep 40; exit" SIGTERM
        while true
        do
          echo Running
          sleep 1
        done
